import {
  IconAward,
  IconBoxMultiple,
  IconPoint,
  IconAlertCircle,
  IconNotes,
  IconCalendar,
  IconMail,
  IconTicket,
  IconEdit,
  IconGitMerge,
  IconCurrencyDollar,
  IconApps,
  IconFileDescription,
  IconFileDots,
  IconFiles,
  IconBan,
  IconStar,
  IconMoodSmile,
  IconBorderAll,
  IconBorderHorizontal,
  IconBorderInner,
  IconBorderVertical,
  IconBorderTop,
  IconUserCircle,
  IconPackage,
  IconMessage2,
  IconBasket,
  IconChartLine,
  IconChartArcs,
  IconChartCandle,
  IconChartArea,
  IconChartDots,
  IconChartDonut3,
  IconChartRadar,
  IconLogin,
  IconUserPlus,
  IconRotate,
  IconBox,
  IconAperture,
  IconShoppingCart,
  IconHelp,
  IconBoxAlignBottom,
  IconBoxAlignLeft,
  IconLayout,
  IconZoomCode,
  IconSettings,
  IconBorderStyle2,
  IconAppWindow,
  IconLockAccess,
  IconHomePlus,
  IconBrandCodepen,
} from '@tabler/icons';

import { uniqueId } from 'lodash';

const Menuitems = [
  {
    navlabel: true,
    subheader: 'Home',
  },
  {
    id: uniqueId(),
    title: 'ภาพรวมสถานะโครงการ',
    icon: IconAperture,
    href: '/dashboards/modern',
    chipColor: 'secondary',
  },
  {
    navlabel: true,
    subheader: 'บันทึกข้อมูลเข้าระบบ',
  },
  {
    id: uniqueId(),
    title: 'สร้างโครงการใหม่',
    icon: IconHomePlus,
    href: '/forms/form-project',
  },
  {
    id: uniqueId(),
    title: 'สร้างข้อมูลชั้นของโครงการ',
    icon: IconBrandCodepen,
    href: '/forms/form-section',
  },
  {
    id: uniqueId(),
    title: 'สร้างข้อมูล Component',
    icon: IconBrandCodepen,
    href: '/forms/form-component',
  },
  {
    id: uniqueId(),
    title: 'QR Code Reader',
    icon: IconZoomCode,
    href: '/forms/form-qr-code-reader',
  },
  {
    id: uniqueId(),
    title: 'QR Code Print',
    icon: IconZoomCode,
    href: '/pages/qr-code',
  },
  // {
  //   id: uniqueId(),
  //   title: 'Form Elements',
  //   icon: IconApps,
  //   href: '/forms/form-elements/autocomplete',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'Autocomplete',
  //       icon: IconPoint,
  //       href: '/forms/form-elements/autocomplete',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Button',
  //       icon: IconPoint,
  //       href: '/forms/form-elements/button',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Checkbox',
  //       icon: IconPoint,
  //       href: '/forms/form-elements/checkbox',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Radio',
  //       icon: IconPoint,
  //       href: '/forms/form-elements/radio',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Date Time',
  //       icon: IconPoint,
  //       href: '/forms/form-elements/date-time',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Slider',
  //       icon: IconPoint,
  //       href: '/forms/form-elements/slider',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Switch',
  //       icon: IconPoint,
  //       href: '/forms/form-elements/switch',
  //     },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Form Validation',
  //   icon: IconFiles,
  //   href: '/forms/form-validation',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Quill Editor',
  //   icon: IconEdit,
  //   href: '/forms/quill-editor',
  // },
  // {
  //   navlabel: true,
  //   subheader: 'Tables',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Basic',
  //   icon: IconBorderAll,
  //   href: '/tables/basic',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Collapsible',
  //   icon: IconBorderHorizontal,
  //   href: '/tables/collapsible',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Enhanced',
  //   icon: IconBorderInner,
  //   href: '/tables/enhanced',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Fixed Header',
  //   icon: IconBorderVertical,
  //   href: '/tables/fixed-header',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Pagination',
  //   icon: IconBorderTop,
  //   href: '/tables/pagination',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Search',
  //   icon: IconBorderStyle2,
  //   href: '/tables/search',
  // },
  {
    navlabel: true,
    subheader: 'Auth',
  },
  // {
  //   id: uniqueId(),
  //   title: 'Login',
  //   icon: IconLogin,
  //   href: '/auth/login',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'Boxed Login',
  //       icon: IconPoint,
  //       href: '/auth/login',
  //     },
  //   ],
  // },
  {
    id: uniqueId(),
    title: 'ลงทะเบียนผู้ใช้งาน',
    icon: IconUserPlus,
    href: '/auth/register',
    children: [
      {
        id: uniqueId(),
        title: 'ลงทะเบียนผู้ใช้งาน',
        icon: IconPoint,
        href: '/auth/register',
      },
    ],
  },
  // {
  //   id: uniqueId(),
  //   title: 'Account Setting',
  //   icon: IconUserCircle,
  //   href: '/pages/account-settings',
  // },
  // {
  //   navlabel: true,
  //   subheader: 'Other',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Menu Level',
  //   icon: IconBoxMultiple,
  //   href: '/dashboards/starter',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'Level 1',
  //       icon: IconPoint,
  //       href: '/l1',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Level 1.1',
  //       icon: IconPoint,
  //       href: '/l1.1',
  //       children: [
  //         {
  //           id: uniqueId(),
  //           title: 'Level 2',
  //           icon: IconPoint,
  //           href: '/l2',
  //         },
  //         {
  //           id: uniqueId(),
  //           title: 'Level 2.1',
  //           icon: IconPoint,
  //           href: '/l2.1',
  //           children: [
  //             {
  //               id: uniqueId(),
  //               title: 'Level 3',
  //               icon: IconPoint,
  //               href: '/l3',
  //             },
  //             {
  //               id: uniqueId(),
  //               title: 'Level 3.1',
  //               icon: IconPoint,
  //               href: '/l3.1',
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //   ],
  // },
];

export default Menuitems;